-- CREATE THE DATA BASE
-- THEN CREATE USER
-- LAST GIVE THE USER THE PRIVILEAGE (THE WHAT CAN HE DO)
-- SELECT IS FOR READ ONLY 

CREATE DATABASE IF NOT EXISTS hbtn_0d_2;
CREATE USER IF NOT EXISTS 'user_0d_2'@'localhost' IDENTIFIED BY 'user_0d_2_pwd';

GRANT SELECT ON hbtn_0d_2.*
TO 'user_0d_2'@'localhost';
