-- 

-- HERE I WILL CREATE DATABASE 
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;

-- THEN I WILL USE THIS DATABASE BY COMMAND (USE)
USE hbtn_0d_usa;

-- NOW I AM IN hbtn_0d_usa DATABASE SO I WILL CREATE TABLE
CREATE TABLE IF NOT EXISTS states (
    id INT NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
    name VARCHAR(256) NOT NULL
);
